services:
  backend:
    image: node:16
    working_dir: /app
    volumes:
      - ./backend:/app
    command: bash -c "chmod +x npmSetupBackend.sh && ./npmSetupBackend.sh"
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development

  frontend:
    image: node:16
    working_dir: /app
    command: bash -c "chmod +x npmSetup.sh && ./npmSetup.sh"
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    depends_on:
      - backend

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default_prod.conf
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
