services:
  db:
    image: postgres:latest
    volumes:
      - ./db/postgres-data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: tbd_db
      POSTGRES_USER: tbd_user
      POSTGRES_PASSWORD: 9wnniIakZD9mVctI

  backend:
    image: node:16
    working_dir: /app
    volumes:
      - ./backend:/app
    command: bash -c "chmod +x npmSetupBackend.sh && ./npmSetupBackend.sh"
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
    depends_on:
      - db

  frontend:
    image: node:16
    working_dir: /app
    command: bash -c "chmod +x npmSetup.sh && ./npmSetup.sh"
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    depends_on:
      - backend

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/default_prod.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - frontend