name: Deploy
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          name: id_rsa
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
          config: ${{ secrets.SSH_CONFIG }}
      - name: Check out code
        uses: actions/checkout@v2
      - name: Deploy with rsync
        run: |
          ls -a
          ssh ${{ secrets.SSH_HOST }} 'cd /home/$USER/tbd-develop; rm -rf frontend backend'
          rsync -auvPz ./ ${{ secrets.SSH_HOST }}:/home/${{ secrets.SSH_USER }}/tbd-develop/
          ssh ${{ secrets.SSH_HOST }} 'cd /home/$USER/tbd-develop/backend; touch .env.local; echo OPENAI_API_KEY=\"${{ secrets.OPENAI_API_KEY }}\" >> .env.local'
          ssh ${{ secrets.SSH_HOST }} 'cd /home/$USER/tbd-develop; docker-compose down --rmi all --volumes --remove-orphans;  docker-compose -f compose.yaml up -d --build'
